'use client';

import { useRef } from 'react';

interface PrintReadingProps {
    number: number;
    meaning: string;
    love?: string;
    career?: string;
    twinFlame?: string;
    luckyColor?: string;
    chakra?: string;
}

export function PrintReading({
    number,
    meaning,
    love,
    career,
    twinFlame,
    luckyColor,
    chakra
}: PrintReadingProps) {
    const contentRef = useRef<HTMLDivElement>(null);

    const handlePrint = () => {
        const printContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Angel Number ${number} - Spirit Numeral</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { 
            font-family: Georgia, 'Times New Roman', serif; 
            padding: 40px; 
            max-width: 800px; 
            margin: 0 auto;
            color: #1a1a1a;
            line-height: 1.6;
          }
          .header { 
            text-align: center; 
            margin-bottom: 40px;
            padding-bottom: 20px;
            border-bottom: 2px solid #d4a853;
          }
          .number { 
            font-size: 72px; 
            font-weight: bold; 
            color: #d4a853;
            margin-bottom: 10px;
          }
          .title { 
            font-size: 24px; 
            color: #666;
            font-style: italic;
          }
          .section { 
            margin-bottom: 30px;
          }
          .section-title { 
            font-size: 18px;
            font-weight: bold;
            color: #d4a853;
            margin-bottom: 10px;
            text-transform: uppercase;
            letter-spacing: 1px;
          }
          .section-content {
            font-size: 14px;
            color: #333;
          }
          .meta {
            display: flex;
            gap: 20px;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #eee;
          }
          .meta-item {
            font-size: 12px;
            color: #666;
          }
          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid #d4a853;
            text-align: center;
            font-size: 12px;
            color: #999;
          }
          @media print {
            body { padding: 20px; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="number">${number}</div>
          <div class="title">Angel Number Reading</div>
        </div>
        
        <div class="section">
          <div class="section-title">Core Meaning</div>
          <div class="section-content">${meaning}</div>
        </div>
        
        ${love ? `
        <div class="section">
          <div class="section-title">Love & Relationships</div>
          <div class="section-content">${love}</div>
        </div>
        ` : ''}
        
        ${career ? `
        <div class="section">
          <div class="section-title">Career & Purpose</div>
          <div class="section-content">${career}</div>
        </div>
        ` : ''}
        
        ${twinFlame ? `
        <div class="section">
          <div class="section-title">Twin Flame Connection</div>
          <div class="section-content">${twinFlame}</div>
        </div>
        ` : ''}
        
        ${(luckyColor || chakra) ? `
        <div class="meta">
          ${luckyColor ? `<div class="meta-item"><strong>Lucky Color:</strong> ${luckyColor}</div>` : ''}
          ${chakra ? `<div class="meta-item"><strong>Active Chakra:</strong> ${chakra}</div>` : ''}
        </div>
        ` : ''}
        
        <div class="footer">
          <p>Generated by Spirit Numeral • spiritnumeral.com</p>
          <p>Your personal angel number reading • ${new Date().toLocaleDateString()}</p>
        </div>
      </body>
      </html>
    `;

        const printWindow = window.open('', '_blank');
        if (printWindow) {
            printWindow.document.write(printContent);
            printWindow.document.close();
            printWindow.focus();
            setTimeout(() => {
                printWindow.print();
            }, 250);
        }
    };

    const handleDownload = () => {
        const content = `
ANGEL NUMBER ${number} READING
================================
Generated by Spirit Numeral
${new Date().toLocaleDateString()}

CORE MEANING
------------
${meaning}

${love ? `LOVE & RELATIONSHIPS
--------------------
${love}

` : ''}${career ? `CAREER & PURPOSE
----------------
${career}

` : ''}${twinFlame ? `TWIN FLAME CONNECTION
---------------------
${twinFlame}

` : ''}${luckyColor ? `Lucky Color: ${luckyColor}
` : ''}${chakra ? `Active Chakra: ${chakra}
` : ''}
================================
Visit spiritnumeral.com for more insights
    `.trim();

        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `angel-number-${number}-reading.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <div ref={contentRef} className="flex items-center gap-2">
            <button
                onClick={handlePrint}
                className="flex items-center gap-2 px-4 py-2 rounded-lg bg-card border border-default text-secondary hover:text-amber-600 hover:border-amber-500/50 transition-all text-sm"
            >
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="6 9 6 2 18 2 18 9" />
                    <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" />
                    <rect width="12" height="8" x="6" y="14" />
                </svg>
                <span>Print</span>
            </button>
            <button
                onClick={handleDownload}
                className="flex items-center gap-2 px-4 py-2 rounded-lg bg-card border border-default text-secondary hover:text-amber-600 hover:border-amber-500/50 transition-all text-sm"
            >
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                    <polyline points="7 10 12 15 17 10" />
                    <line x1="12" x2="12" y1="15" y2="3" />
                </svg>
                <span>Download</span>
            </button>
        </div>
    );
}
